
server:
  port: 8798

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
 cloud:
  gateway:
   httpserver:
    wiretap: true
   httpclient:
    wiretap: true
    ssl:
     useInsecureTrustManager: true
   routes:
   - id: registration
     uri: http://localhost:9091
     predicates:
       - Path=/registration

   - id: auth
     uri: http://localhost:9091
     predicates:
       - Path=/auth