server:
  port: 8798

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
  file.name: logGateway.txt

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: /
          uri: http://localhost:9091
          predicates:
            - Path=/

        - id: registration
          uri: http://localhost:9091
          predicates:
            - Path=/registration

        - id: login
          uri: http://localhost:9091
          predicates:
            - Path=/login

        - id: insurance
          uri: http://localhost:9090
          predicates:
            - Path=/insurance/**

        - id: /styles/css/
          uri: http://localhost:9091
          predicates:
            - Path=/styles/css/**

        - id: /images/
          uri: http://localhost:9091
          predicates:
            - Path=/images/**

        - id: /js/
          uri: http://localhost:9091
          predicates:
            - Path=/js/**

