server:
  port: 9090
jwt:
  secret: hfuei239u88ewhun231jlmhf321
  lifetime: 10m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance
    username: root
    password: a_l1re2ad3e2ad1
  main:
    allow-circular-references: true
logging:
  file.name: logInsuranceService.txt
