server:
  port: 9091
jwt:
  secret: fkpoewj0pjg0j4owifjoilpfe
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: postgres
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false
  application:
    name: authService