server:
  port: 9091
jwt:
  secret: zalupaNegra
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: postgres
  main:
    allow-circular-references: true